# Workflow para build e deploy do Next.js estático no GitHub Pages

name: Deploy Next.js site to Pages

on:
  # Executa em pushes para o branch principal (ajuste se seu branch for outro, ex: master)
  push:
    branches: ["main"]

  # Permite executar este workflow manualmente pela aba Actions no GitHub
  workflow_dispatch:

# Define permissões para o GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente, cancelando execuções anteriores
# Isso evita corridas se você fizer push de múltiplos commits rapidamente
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detectar Gerenciador de Pacotes
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "::error title=Gerenciador de pacotes não suportado::Não foi possível detectar yarn ou npm."
            exit 1
          fi

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Use a versão do Node.js compatível com seu projeto
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Instalar Dependências
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build do Next.js
        # O next.config.js já deve ter output: "export" e basePath/assetPrefix configurados
        run: ${{ steps.detect-package-manager.outputs.manager }} run build

      - name: Upload do Artefato
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz upload do diretório "out" gerado pelo build
          path: ./out

  # Job de Deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

